/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import Controlador.ControladorVehiculos;
import Modelo.Empleados;
import Modelo.VehiculosDisponibles;
import Modelo.VehiculosVendidos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author Usuario
 */

public class InterfazEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazVehiculosDisponibles
     */
     public InterfazEstadisticas(Empleados e, String vistas) {
        
        this.e = e;
        this.setResizable(false);
        cv = new ControladorVehiculos();
        listaOficial = cv.getTodosVendidos();
        initComponents();
        this.posYButton = 20;
        this.posYLabel = 50;
        listaBotones = new ArrayList<JButton>();
        listaLabels = new ArrayList<JLabel>();
        System.out.println(this.jScrollPane1.getViewport().getSize());
        this.jPanel4.setPreferredSize(new Dimension(500, 1000));
        this.jlVistas.setText(vistas);     
                this.setLocationRelativeTo(null);
        this.jPanel9.setBackground(Color.yellow);
        this.jlVistas.setText(vistas); 
        
    }
      public InterfazEstadisticas(Empleados e, int size, String vistas) {
      
        this.e = e;
        this.size = size;
        this.setResizable(false);
        cv = new ControladorVehiculos();
        listaOficial = cv.getTodosVendidos();
        initComponents();
        this.posYButton = 20;
        this.posYLabel = 50;
        listaBotones = new ArrayList<JButton>();
        listaLabels = new ArrayList<JLabel>();
        this.jlStock.setText(String.valueOf(size) + "/50");
        System.out.println(this.jScrollPane1.getViewport().getSize());
        //this.jPanel4.setPreferredSize(new Dimension(500, 1000));
        this.jlVistas.setText(vistas);     
                this.setLocationRelativeTo(null);
        this.jPanel8.setBackground(Color.yellow);
        
    }
    public InterfazEstadisticas(Empleados e) {
      
        this.e = e;
        this.setResizable(false);
        cv = new ControladorVehiculos();
        listaOficial = cv.getTodosVendidos();
        initComponents();
        this.posYButton = 20;
        this.posYLabel = 50;
        listaBotones = new ArrayList<JButton>();
        listaLabels = new ArrayList<JLabel>();
        System.out.println(this.jScrollPane1.getViewport().getSize());
        this.jPanel4.setPreferredSize(new Dimension(500, 1000));
        this.jlVistas.setText("0");
        
                this.setLocationRelativeTo(null);
        this.jPanel8.setBackground(Color.yellow);

        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlCochesVendidos = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlCochesDisponibles = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlRevisiones = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jlInformes = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jlClientes = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jlProveedores = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlVistas = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbListaEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(355, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jlCochesVendidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlCochesVendidos.setText("Coches Vendidos");
        jlCochesVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCochesVendidosMouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listaCoche.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jlCochesVendidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCochesVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jlCochesDisponibles.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlCochesDisponibles.setText("Coches Disponibles");
        jlCochesDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCochesDisponiblesMouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jlCochesDisponibles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlCochesDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jlRevisiones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlRevisiones.setText("Revisiones");
        jlRevisiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRevisionesMouseClicked(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jlRevisiones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jlRevisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jlInformes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlInformes.setText("Gráficos");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadistica.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jlInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jlInformes)
                        .addGap(21, 21, 21))))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jlClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlClientes.setText("Clientes");
        jlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlClientesMouseClicked(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jlClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jlProveedores.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlProveedores.setText("Pedidos");
        jlProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlProveedoresMouseClicked(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-proveedores.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlProveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche2.png"))); // NOI18N

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("en el concesionario");

        jlStock.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlStock.setText("45 / 50");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("vistos hoy");

        jlVistas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlVistas.setText("6");

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 255, 0));
        jButton12.setText("i");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-cerrar-sesion-png-6.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlVistas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlVistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(500000, 500000));
        jPanel4.setLayout(null);
        jScrollPane1.setViewportView(jPanel4);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ESTADÍSTICAS");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche3.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("CONCESIONARIO");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("LA RUEDA S.A");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver gráfico:", "Coches Vendidos por marca", "Coches Vendidos por modelo", "Colores mas populares" }));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setText("Buscar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Guardar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbListaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        jbListaEmpleados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbListaEmpleados.setText("Lista Empleados");
        jbListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbListaEmpleados))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbListaEmpleados)
                                .addGap(9, 9, 9)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jButton13))
                            .addComponent(jButton1))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Usuario: "+e.getEmUsuario()+"\n"+"Rol: "+e.getEmRol());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jlCochesVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCochesVendidosMouseClicked
        // TODO add your handling code here:
        InterfazVehiculosVendidos iv = new InterfazVehiculosVendidos(this.e, this.jlVistas.getText(), size);
        iv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlCochesVendidosMouseClicked

    private void jlRevisionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRevisionesMouseClicked
        // TODO add your handling code here:
        InterfazRevisiones ir = new InterfazRevisiones(this.e, this.jlVistas.getText(), size);
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlRevisionesMouseClicked

    private void jlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlClientesMouseClicked
        // TODO add your handling code here:
         InterfazClientes ic = new InterfazClientes(this.e, this.jlVistas.getText(), size);
        ic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlClientesMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        InterfazLogin il = new InterfazLogin();
        il.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.jPanel4.removeAll();
         String yearS = JOptionPane.showInputDialog(null, "Introduce el año de la consulta: ");
         
        List<VehiculosVendidos> lBMW = cv.buscarPorMarca("BMW");
        List<VehiculosVendidos> lAudi = cv.buscarPorMarca("Audi");
        List<VehiculosVendidos> lSeat = cv.buscarPorMarca("Seat");
        List<VehiculosVendidos> lTotal = cv.getTodosVendidos();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String opcionFiltrado = (String) this.jComboBox1.getSelectedItem();
        int year = Integer.parseInt(yearS);
        switch(opcionFiltrado){
            case "Coches Vendidos por marca":
                      
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 0), "BMW", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 0), "Audi", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 0), "Seat", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 1), "BMW", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 1), "Audi", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 1), "Seat", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 2), "BMW", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 2), "Audi", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 2), "Seat", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 3), "BMW", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 3), "Audi", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 3), "Seat", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 4), "BMW", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 4), "Audi", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 4), "Seat", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 5), "BMW", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 5), "Audi", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 5), "Seat", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 6), "BMW", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 6), "Audi", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 6), "Seat", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 7), "BMW", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 7), "Audi", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 7), "Seat", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 8), "BMW", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 8), "Audi", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 8), "Seat", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 9), "BMW", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 9), "Audi", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 9), "Seat", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 10), "BMW", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 10), "Audi", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 10), "Seat", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lBMW, year, 11), "BMW", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lAudi, year, 11), "Audi", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(lSeat, year, 11), "Seat", "Diciembre");

                 chart = ChartFactory.createBarChart(
                        "Coches Vendidos",
                        "Mes",
                        "Numero de Coches",
                        dataset,
                        PlotOrientation.VERTICAL, true, true, false
                );
                 break;
            case "Coches Vendidos por modelo":
                String marc = JOptionPane.showInputDialog(null, "Introduce la marca: ");
                List<VehiculosVendidos> listaAux = null;
                String[] modelos = new String[3];
                if(marc.equals("BMW")){
                    listaAux = lBMW;
                    modelos[0] = "320";
                    modelos[1] = "330";
                    modelos[2] = "X5";
                }else if(marc.equals("Seat")){
                    listaAux = lSeat;
                    modelos[0] = "Leon";
                    modelos[1] = "Ibiza";
                    modelos[2] = "Arona";
                }else if(marc.equals("Audi")){
                    listaAux = lAudi;
                    modelos[0] = "A3";
                    modelos[1] = "A5";
                    modelos[2] = "A7";
                }else{
                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                }
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 0, modelos[0]), modelos[0], "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 0, modelos[1]), modelos[1], "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 0, modelos[2]), modelos[2], "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 1, modelos[0]), modelos[0], "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 1,modelos[1]), modelos[1], "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 1,modelos[2]), modelos[2], "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 2,modelos[0]), modelos[0], "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 2,modelos[1]), modelos[1], "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 2,modelos[2]), modelos[2], "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 3,modelos[0]), modelos[0], "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 3,modelos[1]), modelos[1], "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 3,modelos[2]), modelos[2], "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 4,modelos[0]), modelos[0], "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 4,modelos[1]), modelos[1], "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 4,modelos[2]), modelos[2], "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 5,modelos[0]), modelos[0], "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 5,modelos[1]), modelos[1], "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 5,modelos[2]), modelos[2], "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 6,modelos[0]), modelos[0], "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 6,modelos[1]), modelos[1], "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 6,modelos[2]), modelos[2], "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 7,modelos[0]), modelos[0], "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 7,modelos[1]), modelos[1], "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 7,modelos[2]), modelos[2], "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 8,modelos[0]), modelos[0], "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 8,modelos[1]), modelos[1], "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 8,modelos[2]), modelos[2], "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 9,modelos[0]), modelos[0], "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 9,modelos[1]), modelos[1], "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 9,modelos[2]), modelos[2], "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 10,modelos[0]), modelos[0], "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 10,modelos[1]), modelos[1], "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 10,modelos[2]), modelos[2], "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 11,modelos[0]), modelos[0], "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 11,modelos[1]), modelos[1], "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos(listaAux, year, 11,modelos[2]), modelos[2], "Diciembre");
                  chart = ChartFactory.createBarChart(
                        "Coches Vendidos: "+marc,
                        "Mes",
                        "Numero de Coches",
                        dataset,
                        PlotOrientation.VERTICAL, true, true, false
                );
                break;
            case "Colores mas populares":
                  dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 0), "Negro", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 0), "Azul", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 0), "Blanco", "Enero");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 0), "Amarillo", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 0), "Marron", "Enero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 0), "Verde", "Enero");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 1), "Negro", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 1), "Azul", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 1), "Blanco", "Febrero");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 1), "Amarillo", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 1), "Marron", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 1), "Verde", "Febrero");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 2), "Negro", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 2), "Azul", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 2), "Blanco", "Marzo");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 2), "Amarillo", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 2), "Marron", "Marzo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 2), "Verde", "Marzo");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 3), "Negro", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 3), "Azul", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 3), "Blanco", "Abril");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 3), "Amarillo", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 3), "Marron", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 3), "Verde", "Abril");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 4), "Negro", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 4), "Azul", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 4), "Blanco", "Mayo");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 4), "Amarillo", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 4), "Marron", "Mayo");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 4), "Verde", "Mayo");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 5), "Negro", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 5), "Azul", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 5), "Blanco", "Junio");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 5), "Amarillo", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 5), "Marron", "Junio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 5), "Verde", "Junio");
                  dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 6), "Negro", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 6), "Azul", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 6), "Blanco", "Julio");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 6), "Amarillo", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 6), "Marron", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 6), "Verde", "Julio");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 7), "Negro", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 7), "Azul", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 7), "Blanco", "Agosto");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 7), "Amarillo", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 7), "Marron", "Agosto");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 7), "Verde", "Agosto");
                  dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 8), "Negro", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 8), "Azul", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 8), "Blanco", "Septiembre");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 8), "Amarillo", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 8), "Marron", "Septiembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 8), "Verde", "Septiembre");
                    dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 9), "Negro", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 9), "Azul", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 9), "Blanco", "Octubre");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 9), "Amarillo", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 9), "Marron", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 9), "Verde", "Octubre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 10), "Negro", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 10), "Azul", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 10), "Blanco", "Noviembre");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 10), "Amarillo", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 10), "Marron", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 10), "Verde", "Noviembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Negro",lTotal, year, 11), "Negro", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Azul",lTotal, year, 11), "Azul", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Blanco",lTotal, year, 11), "Blanco", "Diciembre");
                 dataset.addValue((double) cv.obtenerNumeroVendidos("Amarillo",lTotal, year, 11), "Amarillo", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Marron",lTotal, year, 11), "Marron", "Diciembre");
                dataset.addValue((double) cv.obtenerNumeroVendidos("Verde",lTotal, year, 11), "Verde", "Diciembre");
                  chart = ChartFactory.createBarChart(
                        "Coches Vendidos por color",
                        "Mes",
                        "Numero de Coches",
                        dataset,
                        PlotOrientation.VERTICAL, true, true, false
                );
                break;
        }
      
       ChartPanel panel = new ChartPanel(chart);
       panel.setBounds(this.jPanel4.getBounds());
       this.jScrollPane1.setEnabled(false);
       //panel.setPreferredSize(this.jScrollPane1.getPreferredSize());
       this.jPanel4.add(panel);
       panel.setMouseWheelEnabled(true);
       
       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int width = 1040;   
         int height = 780;   
         
         JFileChooser fileChooser = new JFileChooser();
         int seleccion = fileChooser.showSaveDialog(this);
         if (seleccion == JFileChooser.APPROVE_OPTION){
                File fichero = fileChooser.getSelectedFile();
             try {
                 ChartUtilities.saveChartAsJPEG(fichero, chart, width, height);
             } catch (IOException ex) {
                 Logger.getLogger(InterfazEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
             }
           }
         JOptionPane.showMessageDialog(null, "Imagen Guardada");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlProveedoresMouseClicked
        // TODO add your handling code here:
        
        InterfazPedidos ip = new InterfazPedidos(this.e, this.jlVistas.getText(), size);
        ip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlProveedoresMouseClicked

    private void jbListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaEmpleadosActionPerformed
        // TODO add your handling code here:
        if(this.e.getEmRol().equals("Empleado")){
            JOptionPane.showMessageDialog(null, "No tienes permiso para ver esto");
            return;
        }
        InterfazListaEmpleados il = new InterfazListaEmpleados(this.e);
        il.setVisible(true);
    }//GEN-LAST:event_jbListaEmpleadosActionPerformed

    private void jlCochesDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCochesDisponiblesMouseClicked
        // TODO add your handling code here:
        InterfazVehiculosDisponibles iv = new InterfazVehiculosDisponibles(this.e, this.jlVistas.getText());
        iv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlCochesDisponiblesMouseClicked

   
    /**
     * @param args the command line arguments
     */
   
    ControladorVehiculos cv;
    List<VehiculosVendidos> listaOficial;
    private int posYButton;
    private int posYLabel;
    ArrayList<JButton> listaBotones;
    ArrayList<JLabel> listaLabels;
    private Empleados e;
    JFreeChart chart;
    private int size;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbListaEmpleados;
    private javax.swing.JLabel jlClientes;
    private javax.swing.JLabel jlCochesDisponibles;
    private javax.swing.JLabel jlCochesVendidos;
    private javax.swing.JLabel jlInformes;
    private javax.swing.JLabel jlProveedores;
    private javax.swing.JLabel jlRevisiones;
    private javax.swing.JLabel jlStock;
    private javax.swing.JLabel jlVistas;
    // End of variables declaration//GEN-END:variables
}
