package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1



/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private String numPieza;
     private String descrPieza;
     private String marcaPieza;
     private Integer numPedido;

    public Almacen() {
    }

	
    public Almacen(String numPieza) {
        this.numPieza = numPieza;
    }
    public Almacen(String numPieza, String descrPieza, String marcaPieza, Integer numPedido) {
       this.numPieza = numPieza;
       this.descrPieza = descrPieza;
       this.marcaPieza = marcaPieza;
       this.numPedido = numPedido;
    }
   
    public String getNumPieza() {
        return this.numPieza;
    }
    
    public void setNumPieza(String numPieza) {
        this.numPieza = numPieza;
    }
    public String getDescrPieza() {
        return this.descrPieza;
    }
    
    public void setDescrPieza(String descrPieza) {
        this.descrPieza = descrPieza;
    }
    public String getMarcaPieza() {
        return this.marcaPieza;
    }
    
    public void setMarcaPieza(String marcaPieza) {
        this.marcaPieza = marcaPieza;
    }
    public Integer getNumPedido() {
        return this.numPedido;
    }
    
    public void setNumPedido(Integer numPedido) {
        this.numPedido = numPedido;
    }




}


