package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private byte clienId;
     private int clienPasaporte;
     private String clienHistorialCompras;
     private String clienNombre;
     private String clienApellido;
     private String clienDireccion;
     private String clienGenero;
     private String clienCorreo;
     private Byte clienEdad;
     private String telefono;

    public Clientes() {
    }

	
    public Clientes(byte clienId, int clienPasaporte, String clienNombre, String clienApellido, String telefono) {
        this.clienId = clienId;
        this.clienPasaporte = clienPasaporte;
        this.clienNombre = clienNombre;
        this.clienApellido = clienApellido;
        this.telefono = telefono;
    }
    public Clientes(byte clienId, int clienPasaporte, String clienHistorialCompras, String clienNombre, String clienApellido, String clienDireccion, String clienGenero, String clienCorreo, Byte clienEdad, String telefono) {
       this.clienId = clienId;
       this.clienPasaporte = clienPasaporte;
       this.clienHistorialCompras = clienHistorialCompras;
       this.clienNombre = clienNombre;
       this.clienApellido = clienApellido;
       this.clienDireccion = clienDireccion;
       this.clienGenero = clienGenero;
       this.clienCorreo = clienCorreo;
       this.clienEdad = clienEdad;
       this.telefono = telefono;
    }
   
    public byte getClienId() {
        return this.clienId;
    }
    
    public void setClienId(byte clienId) {
        this.clienId = clienId;
    }
    public int getClienPasaporte() {
        return this.clienPasaporte;
    }
    
    public void setClienPasaporte(int clienPasaporte) {
        this.clienPasaporte = clienPasaporte;
    }
    public String getClienHistorialCompras() {
        return this.clienHistorialCompras;
    }
    
    public void setClienHistorialCompras(String clienHistorialCompras) {
        this.clienHistorialCompras = clienHistorialCompras;
    }
    public String getClienNombre() {
        return this.clienNombre;
    }
    
    public void setClienNombre(String clienNombre) {
        this.clienNombre = clienNombre;
    }
    public String getClienApellido() {
        return this.clienApellido;
    }
    
    public void setClienApellido(String clienApellido) {
        this.clienApellido = clienApellido;
    }
    public String getClienDireccion() {
        return this.clienDireccion;
    }
    
    public void setClienDireccion(String clienDireccion) {
        this.clienDireccion = clienDireccion;
    }
    public String getClienGenero() {
        return this.clienGenero;
    }
    
    public void setClienGenero(String clienGenero) {
        this.clienGenero = clienGenero;
    }
    public String getClienCorreo() {
        return this.clienCorreo;
    }
    
    public void setClienCorreo(String clienCorreo) {
        this.clienCorreo = clienCorreo;
    }
    public Byte getClienEdad() {
        return this.clienEdad;
    }
    
    public void setClienEdad(Byte clienEdad) {
        this.clienEdad = clienEdad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


