package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int emSsn;
     private String emNombre;
     private String emPoblacion;
     private String emPassword;
     private Byte emAntiguedad;
     private Integer emNominaBase;
     private Integer emTelefono;
     private Byte emEdad;
     private String emUsuario;
     private String emRol;

    public Empleados() {
    }

	
    public Empleados(int emSsn, String emNombre) {
        this.emSsn = emSsn;
        this.emNombre = emNombre;
    }
    public Empleados(int emSsn, String emNombre, String emPoblacion, String emPassword, Byte emAntiguedad, Integer emNominaBase, Integer emTelefono, Byte emEdad, String emUsuario, String emRol) {
       this.emSsn = emSsn;
       this.emNombre = emNombre;
       this.emPoblacion = emPoblacion;
       this.emPassword = emPassword;
       this.emAntiguedad = emAntiguedad;
       this.emNominaBase = emNominaBase;
       this.emTelefono = emTelefono;
       this.emEdad = emEdad;
       this.emUsuario = emUsuario;
       this.emRol = emRol;
    }
   
    public int getEmSsn() {
        return this.emSsn;
    }
    
    public void setEmSsn(int emSsn) {
        this.emSsn = emSsn;
    }
    public String getEmNombre() {
        return this.emNombre;
    }
    
    public void setEmNombre(String emNombre) {
        this.emNombre = emNombre;
    }
    public String getEmPoblacion() {
        return this.emPoblacion;
    }
    
    public void setEmPoblacion(String emPoblacion) {
        this.emPoblacion = emPoblacion;
    }
    public String getEmPassword() {
        return this.emPassword;
    }
    
    public void setEmPassword(String emPassword) {
        this.emPassword = emPassword;
    }
    public Byte getEmAntiguedad() {
        return this.emAntiguedad;
    }
    
    public void setEmAntiguedad(Byte emAntiguedad) {
        this.emAntiguedad = emAntiguedad;
    }
    public Integer getEmNominaBase() {
        return this.emNominaBase;
    }
    
    public void setEmNominaBase(Integer emNominaBase) {
        this.emNominaBase = emNominaBase;
    }
    public Integer getEmTelefono() {
        return this.emTelefono;
    }
    
    public void setEmTelefono(Integer emTelefono) {
        this.emTelefono = emTelefono;
    }
    public Byte getEmEdad() {
        return this.emEdad;
    }
    
    public void setEmEdad(Byte emEdad) {
        this.emEdad = emEdad;
    }
    public String getEmUsuario() {
        return this.emUsuario;
    }
    
    public void setEmUsuario(String emUsuario) {
        this.emUsuario = emUsuario;
    }
    public String getEmRol() {
        return this.emRol;
    }
    
    public void setEmRol(String emRol) {
        this.emRol = emRol;
    }




}


