package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InfoRevisiones generated by hbm2java
 */
public class InfoRevisiones  implements java.io.Serializable {


     private byte revId;
     private String descripcion;
     private int bastidorNum;
     private String piezas;
     private Date fechaRev;
     private Integer precioRev;
     private String loginEmpleado;

    public InfoRevisiones() {
    }

	
    public InfoRevisiones(byte revId, String descripcion, int bastidorNum, String piezas, Date fechaRev, String loginEmpleado) {
        this.revId = revId;
        this.descripcion = descripcion;
        this.bastidorNum = bastidorNum;
        this.piezas = piezas;
        this.fechaRev = fechaRev;
        this.loginEmpleado = loginEmpleado;
    }
    public InfoRevisiones(byte revId, String descripcion, int bastidorNum, String piezas, Date fechaRev, Integer precioRev, String loginEmpleado) {
       this.revId = revId;
       this.descripcion = descripcion;
       this.bastidorNum = bastidorNum;
       this.piezas = piezas;
       this.fechaRev = fechaRev;
       this.precioRev = precioRev;
       this.loginEmpleado = loginEmpleado;
    }
   
    public byte getRevId() {
        return this.revId;
    }
    
    public void setRevId(byte revId) {
        this.revId = revId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getBastidorNum() {
        return this.bastidorNum;
    }
    
    public void setBastidorNum(int bastidorNum) {
        this.bastidorNum = bastidorNum;
    }
    public String getPiezas() {
        return this.piezas;
    }
    
    public void setPiezas(String piezas) {
        this.piezas = piezas;
    }
    public Date getFechaRev() {
        return this.fechaRev;
    }
    
    public void setFechaRev(Date fechaRev) {
        this.fechaRev = fechaRev;
    }
    public Integer getPrecioRev() {
        return this.precioRev;
    }
    
    public void setPrecioRev(Integer precioRev) {
        this.precioRev = precioRev;
    }
    public String getLoginEmpleado() {
        return this.loginEmpleado;
    }
    
    public void setLoginEmpleado(String loginEmpleado) {
        this.loginEmpleado = loginEmpleado;
    }




}


