package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InfoCompra generated by hbm2java
 */
public class InfoCompra  implements java.io.Serializable {


     private int numeroCompra;
     private byte clienId;
     private int numBastidor;
     private Date fechaCompra;
     private int emSsn;

    public InfoCompra() {
    }

	
    public InfoCompra(int numeroCompra, byte clienId, int numBastidor, int emSsn) {
        this.numeroCompra = numeroCompra;
        this.clienId = clienId;
        this.numBastidor = numBastidor;
        this.emSsn = emSsn;
    }
    public InfoCompra(int numeroCompra, byte clienId, int numBastidor, Date fechaCompra, int emSsn) {
       this.numeroCompra = numeroCompra;
       this.clienId = clienId;
       this.numBastidor = numBastidor;
       this.fechaCompra = fechaCompra;
       this.emSsn = emSsn;
    }
   
    public int getNumeroCompra() {
        return this.numeroCompra;
    }
    
    public void setNumeroCompra(int numeroCompra) {
        this.numeroCompra = numeroCompra;
    }
    public byte getClienId() {
        return this.clienId;
    }
    
    public void setClienId(byte clienId) {
        this.clienId = clienId;
    }
    public int getNumBastidor() {
        return this.numBastidor;
    }
    
    public void setNumBastidor(int numBastidor) {
        this.numBastidor = numBastidor;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public int getEmSsn() {
        return this.emSsn;
    }
    
    public void setEmSsn(int emSsn) {
        this.emSsn = emSsn;
    }




}


