package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1



/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private int numPedido;
     private String tipoPedido;
     private String descrPedido;
     private String loginEmpleado;

    public Pedidos() {
    }

	
    public Pedidos(int numPedido, String loginEmpleado) {
        this.numPedido = numPedido;
        this.loginEmpleado = loginEmpleado;
    }
    public Pedidos(int numPedido, String tipoPedido, String descrPedido, String loginEmpleado) {
       this.numPedido = numPedido;
       this.tipoPedido = tipoPedido;
       this.descrPedido = descrPedido;
       this.loginEmpleado = loginEmpleado;
    }
   
    public int getNumPedido() {
        return this.numPedido;
    }
    
    public void setNumPedido(int numPedido) {
        this.numPedido = numPedido;
    }
    public String getTipoPedido() {
        return this.tipoPedido;
    }
    
    public void setTipoPedido(String tipoPedido) {
        this.tipoPedido = tipoPedido;
    }
    public String getDescrPedido() {
        return this.descrPedido;
    }
    
    public void setDescrPedido(String descrPedido) {
        this.descrPedido = descrPedido;
    }
    public String getLoginEmpleado() {
        return this.loginEmpleado;
    }
    
    public void setLoginEmpleado(String loginEmpleado) {
        this.loginEmpleado = loginEmpleado;
    }




}


