package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1



/**
 * VehiculosDisponibles generated by hbm2java
 */
public class VehiculosDisponibles  implements java.io.Serializable {


     private int numBastidor;
     private String matricula;
     private String extras;
     private String color;
     private String marca;
     private String modelo;
     private Integer precio;

    public VehiculosDisponibles() {
    }

	
    public VehiculosDisponibles(int numBastidor, String matricula) {
        this.numBastidor = numBastidor;
        this.matricula = matricula;
    }
    public VehiculosDisponibles(int numBastidor, String matricula, String extras, String color, String marca, String modelo, Integer precio) {
       this.numBastidor = numBastidor;
       this.matricula = matricula;
       this.extras = extras;
       this.color = color;
       this.marca = marca;
       this.modelo = modelo;
       this.precio = precio;
    }
   
    public int getNumBastidor() {
        return this.numBastidor;
    }
    
    public void setNumBastidor(int numBastidor) {
        this.numBastidor = numBastidor;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getExtras() {
        return this.extras;
    }
    
    public void setExtras(String extras) {
        this.extras = extras;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


