package Modelo;
// Generated 15-abr-2019 17:37:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VehiculosVendidos generated by hbm2java
 */
public class VehiculosVendidos  implements java.io.Serializable {


     private int bastidorNum;
     private String matricula;
     private byte clienId;
     private String marca;
     private String modelo;
     private String color;
     private Date fechaCompra;
     private boolean taller;

    public VehiculosVendidos() {
    }

	
    public VehiculosVendidos(int bastidorNum, String matricula, byte clienId, boolean taller) {
        this.bastidorNum = bastidorNum;
        this.matricula = matricula;
        this.clienId = clienId;
        this.taller = taller;
    }
    public VehiculosVendidos(int bastidorNum, String matricula, byte clienId, String marca, String modelo, String color, Date fechaCompra, boolean taller) {
       this.bastidorNum = bastidorNum;
       this.matricula = matricula;
       this.clienId = clienId;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.fechaCompra = fechaCompra;
       this.taller = taller;
    }
   
    public int getBastidorNum() {
        return this.bastidorNum;
    }
    
    public void setBastidorNum(int bastidorNum) {
        this.bastidorNum = bastidorNum;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public byte getClienId() {
        return this.clienId;
    }
    
    public void setClienId(byte clienId) {
        this.clienId = clienId;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public boolean isTaller() {
        return this.taller;
    }
    
    public void setTaller(boolean taller) {
        this.taller = taller;
    }




}


